# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class Agent():
    def setup_method(self):
        chrome_options = Options()
        chrome_options.add_argument('--no-sandbox')
        chrome_options.add_argument('--disable-dev-shm-usage')
        # 用于打开和关闭浏览器窗口
        chrome_options.add_argument('--headless')
        chrome_options.add_argument('--window-size=1920,1050')  # 专门应对无头浏览器中不能最大化屏幕的方案
        self.driver = webdriver.Chrome(options=chrome_options)
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def fetch(self):
        self.driver.get("https://www.pkulaw.com/chl/aec0c211a78989e9bdfb.html")
        # res = self.driver.find_element(By.LINK_TEXT, "现行有效").get_attribute("href")
        title = self.driver.find_element(By.XPATH,"//*[@id='gridleft']/div/div[1]/h2").text.rstrip(' English')
        rele_date = self.driver.find_element(By.XPATH,"//*[@id='gridleft']/div/div[1]/div[2]/ul/li[3]").get_attribute("title")
        effc_date = self.driver.find_element(By.XPATH,"//*[@id='gridleft']/div/div[1]/div[2]/ul/li[4]").get_attribute("title")
        stat_of_auth = self.driver.find_element(By.XPATH,"//*[@id='gridleft']/div/div[1]/div[2]/ul/li[5]/div/span").get_attribute("title")
        lv_of_auth = self.driver.find_element(By.XPATH,"//*[@id='gridleft']/div/div[1]/div[2]/ul/li[6]/div/span").get_attribute("title")
        print('标题：',title,'\n','发布日期：',rele_date,'\n','生效日期',effc_date,'\n','时效性',stat_of_auth,'\n','效力级别',lv_of_auth)


if __name__ == '__main__':
    test = Agent()
    test.setup_method()

    test.fetch()
    test.teardown_method()
